### ISSUE TITLE
node installed but no npm?

### ISSUE THREAD

**Issue by philkunz** [leaningtech/webvm#106]
node seems to be installed but no package manager? Why not?

**Comment by alexp-sssup** [comment]
There is currently a 2GB limit to the disk image size that CheerpX supports, so we cannot cover all the possible user needs.

For our public https://webvm.io deployment we selected a set of application to show case the capabilities of the platform. This selection includes node, since it demonstrates that CheerpX can execute not only static code, but also code dynamically generated by an application at runtime.

If you need a different set of packages you can simply follow the repo README and make your own version of WebVM by modifying the Dockerfile as appropriate.

See here for more information: https://github.com/leaningtech/webvm?tab=readme-ov-file#fork-deploy-customize
