### ISSUE TITLE
how to overlay a local directory into vm?

### ISSUE THREAD

**Issue by YinYongHongYork** [leaningtech/webvm#115]
for example, there's directory named "webvm_local" under root.

then access it as "~/webmv_local" in webvm

**Comment by saarikoski-jules** [comment]
This: `{type:"cheerpOS",dev:"/app",path:"/app"}` should be present in CheerpX.create. This allows you to access files in the root of your server. You will also need to add a file named index.list to your local directory that contains a list of all the filenames in the directory, so that CheerpX can know which files can be found. The files can then be found in `/app`. This directory is read only.

This API is going to change very soon when our new API updates are merged.
