### ISSUE TITLE
[Question] What are the limitations of  webvm ?

### ISSUE THREAD

**Issue by Greatz08** [leaningtech/webvm#150]
It is pretty interesting thing for me but i think it must be having some or maybe lots of limitations so i was just curious to know about it . 
So if possible do list all here or in main repo :-)

**Comment by alexp-sssup** [comment]
There are limitations due to bugs in the x86 emulation and incomplete support for syscalls, but we strive to solve these problems as they arise either in public bug report or in our internal testing and demos.

Another set of limitations comes from the performance impact of virtualization, this said the level of performance is already sufficient for many practical use cases and will further improve down the line.

Moreover WebVM cannot interact directly with resources on your system, such as your local files. This is not necessarily a limitation though, but also a feature of virtualization in the browser sandbox. In the future we plan to integrate with the FileSystem API to make it possible to expose parts of the local filesystem in a controlled fashion. Similar reasoning applies to experimental API such as WebUSB.

Networking limitations are worked around using Tailscale integration, which covers the vast majority of use cases: https://cheerpx.io/docs/guides/Networking

I would recommend joining our Discord for further discussion: https://discord.leaningtech.com
