### ISSUE TITLE
replace xterm.js by another terminal

### ISSUE THREAD

**Issue by Utopiah** [leaningtech/webvm#90]
Hi, really cool project. I'd like to rely on it in order to developer XR content via the Web. I'm already doing so with my own code editor but truth is, I miss Vim proper.

There are existing solution by using Termux on the device but is not immersive, forcing to switch back and forth between code and content. Alternatively one can stream their desktop via WebRTC, edit, live-reload part of the content. Unfortunately that requires another device.

I believe having WebVM instead would open-up a lot of interesting use cases but even "just" being able to live-reload with a proper editor, like Vim, while being properly standalone is already a great value proposition.

Anyway xterm.js might be usable as-is via e.g https://github.com/AdaRoseCannon/aframe-htmlmesh (but I doubt it, relatively complex) or instead replaced by https://github.com/kylebakerio/a-console 

I'm wondering if you have suggestion on how to replace the interface here by something more immersive.

**Comment by nanaian** [comment]
Hello! Rendering WebVM inside A-Frame will be complex, but it sounds pretty cool.

I think the [html component](https://github.com/AdaRoseCannon/aframe-htmlmesh) that you linked may actually work well. It should detect WebVM's xterm.js `canvas` elements and render them as three.js meshes. I'd suggest you go down that route!

I'm going to close this because it's more of a question than an issue, and there shouldn't be any need for us to change anything upstream. I suggest you [join our Discord server](https://discord.leaningtech.com), but if not, let me know how far you get with this idea 👀

**Comment by Utopiah** [comment]
That's the best kind of issues, the ones that can be closed right away because the architecture or stack choices solve it instantly ;) I'll try ASAP and report back here but indeed the canvas was the solution I had in mind.

**Comment by nanaian** [comment]
Awesome. Note that xterm.js isn't deeply integrated into WebVM at all - if you run into trouble with xterm.js, you could find [some other terminal emulator](https://github.com/raphamorim/rio) it could probably be integrated without much work.

**Comment by Utopiah** [comment]
Damn... it worked https://twitter.com/utopiah/status/1723355832652292193 :)
