### ISSUE TITLE
Github Pages artifact upload fails with "Operation not permitted" error

### ISSUE THREAD

**Issue by ebanDev** [leaningtech/webvm#94]
# Summary

When deploying a Github Pages artifact, the upload fails with the error message "Operation not permitted".

# Steps to reproduce

1. Clone the repository.
2. Start the workflow.

# Error code

The deployment fails with the following error message:

chmod: changing permissions of '/webvm_deploy/debian_mini_20231217_7240414833.ext2.c001121.txt': Operation not permitted

Here is my repo : https://github.com/ebanDev/WebsiteTerminal/actions/runs/7240414833/job/19723376563

**Comment by alexp-sssup** [comment]
The error is not fatal. Is something actually not working?

**Comment by ebanDev** [comment]
![image](https://github.com/leaningtech/webvm/assets/57091497/495d8bc9-3770-47a4-9b83-e791fc1b95f8)
Yes, it says on the deploy_to_github_pages step : `Error: Error: No uploaded artifact was found! Please check if there are any errors at build step, or uploaded artifact name is correct.`

**Comment by alexp-sssup** [comment]
Are you sure GH pages are enabled for your fork?

https://github.com/leaningtech/webvm#fork-deploy-customize

**Comment by ebanDev** [comment]
yes I am I wouldn't have created an issue without verifying this 😅On Dec 19, 2023 14:59, Alessandro Pignotti ***@***.***> wrote:
Are you sure GH pages are enabled for your fork?
https://github.com/leaningtech/webvm#fork-deploy-customize

**Comment by nanaian** [comment]
Looks like something broke on GitHub's side - thanks for the report.

https://github.com/orgs/community/discussions/79266 recommended that we upgrade the `actions/upload-pages-artifact` and `actions/deploy-pages` to their [latest](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) versions, but [this doesn't seem to work for us](https://github.com/nanaian/webvm/actions/runs/7276703158). Instead, it seems upgrading `actions/upload-pages-artifact` from v1 to v2 fixes it.

Fixed in https://github.com/leaningtech/webvm/commit/36db7dd37d6d87055a0d1cecfd807de41e5dc419.

**Comment by ebanDev** [comment]
Okay thank you ! :)On Dec 20, 2023 15:45, Alex Bates ***@***.***> wrote:
Looks like something broke on GitHub's side - thanks for the report.
https://github.com/orgs/community/discussions/79266 recommended that we upgrade the actions/upload-pages-artifact and actions/deploy-pages to their latest versions, but this doesn't seem to work for us. Instead, it seems upgrading actions/upload-pages-artifact from v1 to v2 fixes it.
Fixed in 36db7dd.

**Comment by ebanDev** [comment]
Hi ! I tried to fork again the project and to deploy it, but I can't select Github Actions as the source for Pages. When I click on the button simply nothing happens and I get this error code
![image](https://github.com/leaningtech/webvm/assets/57091497/f8514d04-3937-4f57-b328-86364b07c6d5)
