### ISSUE TITLE
example for nodejs environment.

### ISSUE THREAD

**Issue by ganeshkbhat** [leaningtech/webvm#99]
nice. any example of how to use this in nodejs environment. testing it. it is a little slow in the edge browser but works as expected `Version 122.0.2365.66 (Official build) (64-bit)`

**Comment by alexp-sssup** [comment]
WebVM is intended for use in the browser, we might consider adding support for node in the future, but it's not a priority for us.

**Comment by alexp-sssup** [comment]
For further discussion consider joining our Discord: https://discord.gg/yTNZgySKGa

**Comment by bates64** [comment]
@ganeshkbhat We don't really see much reason to support CheerpX (the technology behind WebVM) on Node.js and other non-browser environments, because that implies you have access to existing native solutions such as [node-gyp](https://github.com/nodejs/node-gyp). Sandboxing might be an interesting use case, but there are also solutions for that such as virtualisation.

It might help if you could explain your use-case in more detail.

If you're looking for something isomorphic, e.g. something that implements the CheerpX API on Node.js but using native solutions, let me know.
